<?php

namespace ContainerJlXgLBt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EQNhRqYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eQNhRqY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eQNhRqY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotor' => ['privates', '.errored..service_locator.eQNhRqY.App\\Entity\\Promotor', NULL, 'Cannot autowire service ".service_locator.eQNhRqY": it needs an instance of "App\\Entity\\Promotor" but this type has been excluded in "config/services.yaml".'],
        ], [
            'promotor' => 'App\\Entity\\Promotor',
        ]);
    }
}
