<?php

namespace ContainerJlXgLBt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cx8azIfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cx8azIf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cx8azIf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PromotorController::downloadAction' => ['privates', '.service_locator.zdu7cYm', 'get_ServiceLocator_Zdu7cYmService', true],
            'App\\Controller\\PromotorController::index' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController::new' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController::show' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Controller\\PromotorController::show2' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Controller\\PromotorController::show3' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PromotorController:downloadAction' => ['privates', '.service_locator.zdu7cYm', 'get_ServiceLocator_Zdu7cYmService', true],
            'App\\Controller\\PromotorController:index' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController:new' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController:show' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Controller\\PromotorController:show2' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Controller\\PromotorController:show3' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PromotorController::downloadAction' => '?',
            'App\\Controller\\PromotorController::index' => '?',
            'App\\Controller\\PromotorController::new' => '?',
            'App\\Controller\\PromotorController::show' => '?',
            'App\\Controller\\PromotorController::show2' => '?',
            'App\\Controller\\PromotorController::show3' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PromotorController:downloadAction' => '?',
            'App\\Controller\\PromotorController:index' => '?',
            'App\\Controller\\PromotorController:new' => '?',
            'App\\Controller\\PromotorController:show' => '?',
            'App\\Controller\\PromotorController:show2' => '?',
            'App\\Controller\\PromotorController:show3' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
