<?php

namespace ContainerJlXgLBt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L70CrkYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.l70CrkY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l70CrkY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'promotorRepository' => ['privates', 'App\\Repository\\PromotorRepository', 'getPromotorRepositoryService', true],
        ], [
            'promotorRepository' => 'App\\Repository\\PromotorRepository',
        ]);
    }
}
