<?php

namespace ContainerJlXgLBt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eQNhRqY.App\Entity\Promotor' shared service.
     *
     * @return \App\Entity\Promotor
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eQNhRqY": it needs an instance of "App\\Entity\\Promotor" but this type has been excluded in "config/services.yaml".');
    }
}
