<?php

namespace ContainerQCx6pK7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PromotorController::downloadAction' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromotorController::index' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController::new' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController::show' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Controller\\PromotorController::show2' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PromotorController:downloadAction' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PromotorController:index' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController:new' => ['privates', '.service_locator.l70CrkY', 'get_ServiceLocator_L70CrkYService', true],
            'App\\Controller\\PromotorController:show' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'App\\Controller\\PromotorController:show2' => ['privates', '.service_locator.eQNhRqY', 'get_ServiceLocator_EQNhRqYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PromotorController::downloadAction' => '?',
            'App\\Controller\\PromotorController::index' => '?',
            'App\\Controller\\PromotorController::new' => '?',
            'App\\Controller\\PromotorController::show' => '?',
            'App\\Controller\\PromotorController::show2' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PromotorController:downloadAction' => '?',
            'App\\Controller\\PromotorController:index' => '?',
            'App\\Controller\\PromotorController:new' => '?',
            'App\\Controller\\PromotorController:show' => '?',
            'App\\Controller\\PromotorController:show2' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
