<?php

namespace ContainerQCx6pK7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_LiveCollectionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.live_collection' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Form\Type\LiveCollectionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.live_collection'] = new \Symfony\UX\LiveComponent\Form\Type\LiveCollectionType();
    }
}
