<?php

namespace ContainerQCx6pK7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PromotorRepository' shared autowired service.
     *
     * @return \App\Repository\PromotorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PromotorRepository'] = new \App\Repository\PromotorRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
