<?php

namespace ContainerQCx6pK7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotorTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PromotorType' shared autowired service.
     *
     * @return \App\Form\PromotorType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PromotorType'] = new \App\Form\PromotorType();
    }
}
