<?php

namespace ContainerQCx6pK7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_ComponentHydratorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux.live_component.component_hydrator' shared service.
     *
     * @return \Symfony\UX\LiveComponent\LiveComponentHydrator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['ux.live_component.component_hydrator'] = new \Symfony\UX\LiveComponent\LiveComponentHydrator(($container->privates['serializer'] ?? $container->load('getSerializerService')), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), $container->getEnv('APP_SECRET'));
    }
}
