<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQCx6pK7\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQCx6pK7/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQCx6pK7.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQCx6pK7\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQCx6pK7\App_KernelProdContainer([
    'container.build_hash' => 'QCx6pK7',
    'container.build_id' => '9b567932',
    'container.build_time' => 1681369657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQCx6pK7');
