<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'qr_code_generate' => [['builder', 'data'], ['_controller' => 'Endroid\\QrCodeBundle\\Controller\\GenerateController'], ['data' => '[\\w\\W]+'], [['variable', '/', '[\\w\\W]+', 'data', true], ['variable', '/', '[^/]++', 'builder', true], ['text', '/qr-code']], [], [], []],
    'ux_live_component' => [['_live_component', '_live_action'], ['_live_action' => 'get'], [], [['variable', '/', '[^/]++', '_live_action', true], ['variable', '/', '[^/]++', '_live_component', true], ['text', '/_components']], [], [], []],
    'app_promotor_index' => [[], ['_controller' => 'App\\Controller\\PromotorController::index'], [], [['text', '/admin']], [], [], []],
    'app_promotor_new' => [[], ['_controller' => 'App\\Controller\\PromotorController::new'], [], [['text', '/']], [], [], []],
    'app_promotor_show' => [['id'], ['_controller' => 'App\\Controller\\PromotorController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/promotor']], [], [], []],
    'app_promotor_show2' => [['id'], ['_controller' => 'App\\Controller\\PromotorController::show2'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/qr-promotor']], [], [], []],
    'app_down' => [['id'], ['_controller' => 'App\\Controller\\PromotorController::downloadAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/descargar']], [], [], []],
    'app_qr_codes' => [[], ['_controller' => 'App\\Controller\\PromotorController::verQr'], [], [['text', '/qr/qr-codes']], [], [], []],
];
