<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcK8RXn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcK8RXn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAcK8RXn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAcK8RXn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAcK8RXn\App_KernelDevDebugContainer([
    'container.build_hash' => 'AcK8RXn',
    'container.build_id' => '7bb702ef',
    'container.build_time' => 1681509500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcK8RXn');
